# Site settings
title: Alver's ML Blog
email: 
description: "Decoded activities of mine."
baseurl: "/blog"
url: "https://alversafa.github.io/"
twitter_username: alversafa
github_username:  alversafa

# Build settings
markdown: kramdown
theme: minima

plugins:
- jekyll-seo-tag
