# Site settings
title: Alver's ML Blog
email: 
description: "Decoded latents of mine through spacetime."
baseurl: ""
url: "https://alversafa.github.io/blog"
twitter_username: alversafa
github_username:  alversafa

# Build settings
markdown: kramdown
theme: minima

