# Site settings
title: Safa Alver's Blog
email: 
description: Thoughts of mine sampled through spacetime
baseurl: 
url: "https://alversafa.github.io/"
twitter_username: alversafa
github_username:  alversafa

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

